#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: @nacos.namespace@
#      group: SEATA_GROUP
#      application: seata-server
#      username: nacos
#      password: nacos
#  data-source-proxy-mode: AT
